import { GeistSans } from "geist/font";
import type { Metadata } from "next";

import "./globals.css";
import Footer from "@/components/ui/Footer";
import Navbar from "@/components/ui/Navbar";
import { getSingleType } from "@/lib/strapi";

export const metadata: Metadata = {
  description: "Generated by create next app",
  title: "Create Next App",
};

export default async function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  const {
    github_link,
    instagram_link,
    linkedin_link,
    nav_logo_image,
    twitter_link,
    youtube_link,
  } = await getSingleType("page-shared-data");

  return (
    <html lang="en">
      <body
        className={`${GeistSans.className} relative bg-background pt-20 text-foreground`}
      >
        <Navbar logo={nav_logo_image} />
        <div className="relative z-10 rounded-bl-[50px] rounded-br-[50px] bg-background pb-10">
          {children}
        </div>
        <Footer
          links={{
            github_link,
            instagram_link,
            linkedin_link,
            twitter_link,
            youtube_link,
          }}
          logo={nav_logo_image}
        />
      </body>
    </html>
  );
}
